// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.4
 * source: gogoproto/gogo.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
export namespace gogoproto { }
