// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.17.3
 * source: cosmos/authz/v1beta1/genesis.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../google/protobuf/timestamp";
import * as dependency_2 from "./../../../google/protobuf/any";
import * as dependency_3 from "./../../../gogoproto/gogo";
import * as dependency_4 from "./../../../cosmos_proto/cosmos";
import * as pb_1 from "google-protobuf";
export namespace cosmos.authz.v1beta1 {
    export class GenesisState extends pb_1.Message {
        constructor(data?: any[] | {
            authorization?: GrantAuthorization[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("authorization" in data && data.authorization != undefined) {
                    this.authorization = data.authorization;
                }
            }
        }
        get authorization() {
            return pb_1.Message.getRepeatedWrapperField(this, GrantAuthorization, 1) as GrantAuthorization[];
        }
        set authorization(value: GrantAuthorization[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            authorization?: ReturnType<typeof GrantAuthorization.prototype.toObject>[];
        }) {
            const message = new GenesisState({});
            if (data.authorization != null) {
                message.authorization = data.authorization.map(item => GrantAuthorization.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                authorization?: ReturnType<typeof GrantAuthorization.prototype.toObject>[];
            } = {};
            if (this.authorization != null) {
                data.authorization = this.authorization.map((item: GrantAuthorization) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.authorization !== undefined)
                writer.writeRepeatedMessage(1, this.authorization, (item: GrantAuthorization) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GenesisState {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GenesisState();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.authorization, () => pb_1.Message.addToRepeatedWrapperField(message, 1, GrantAuthorization.deserialize(reader), GrantAuthorization));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GenesisState {
            return GenesisState.deserialize(bytes);
        }
    }
    export class GrantAuthorization extends pb_1.Message {
        constructor(data?: any[] | {
            granter?: string;
            grantee?: string;
            authorization?: dependency_2.google.protobuf.Any;
            expiration?: dependency_1.google.protobuf.Timestamp;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("granter" in data && data.granter != undefined) {
                    this.granter = data.granter;
                }
                if ("grantee" in data && data.grantee != undefined) {
                    this.grantee = data.grantee;
                }
                if ("authorization" in data && data.authorization != undefined) {
                    this.authorization = data.authorization;
                }
                if ("expiration" in data && data.expiration != undefined) {
                    this.expiration = data.expiration;
                }
            }
        }
        get granter() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set granter(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get grantee() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set grantee(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get authorization() {
            return pb_1.Message.getWrapperField(this, dependency_2.google.protobuf.Any, 3) as dependency_2.google.protobuf.Any;
        }
        set authorization(value: dependency_2.google.protobuf.Any) {
            pb_1.Message.setWrapperField(this, 3, value);
        }
        get expiration() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 4) as dependency_1.google.protobuf.Timestamp;
        }
        set expiration(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 4, value);
        }
        static fromObject(data: {
            granter?: string;
            grantee?: string;
            authorization?: ReturnType<typeof dependency_2.google.protobuf.Any.prototype.toObject>;
            expiration?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        }) {
            const message = new GrantAuthorization({});
            if (data.granter != null) {
                message.granter = data.granter;
            }
            if (data.grantee != null) {
                message.grantee = data.grantee;
            }
            if (data.authorization != null) {
                message.authorization = dependency_2.google.protobuf.Any.fromObject(data.authorization);
            }
            if (data.expiration != null) {
                message.expiration = dependency_1.google.protobuf.Timestamp.fromObject(data.expiration);
            }
            return message;
        }
        toObject() {
            const data: {
                granter?: string;
                grantee?: string;
                authorization?: ReturnType<typeof dependency_2.google.protobuf.Any.prototype.toObject>;
                expiration?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            } = {};
            if (this.granter != null) {
                data.granter = this.granter;
            }
            if (this.grantee != null) {
                data.grantee = this.grantee;
            }
            if (this.authorization != null) {
                data.authorization = this.authorization.toObject();
            }
            if (this.expiration != null) {
                data.expiration = this.expiration.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.granter === "string" && this.granter.length)
                writer.writeString(1, this.granter);
            if (typeof this.grantee === "string" && this.grantee.length)
                writer.writeString(2, this.grantee);
            if (this.authorization !== undefined)
                writer.writeMessage(3, this.authorization, () => this.authorization.serialize(writer));
            if (this.expiration !== undefined)
                writer.writeMessage(4, this.expiration, () => this.expiration.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GrantAuthorization {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GrantAuthorization();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.granter = reader.readString();
                        break;
                    case 2:
                        message.grantee = reader.readString();
                        break;
                    case 3:
                        reader.readMessage(message.authorization, () => message.authorization = dependency_2.google.protobuf.Any.deserialize(reader));
                        break;
                    case 4:
                        reader.readMessage(message.expiration, () => message.expiration = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GrantAuthorization {
            return GrantAuthorization.deserialize(bytes);
        }
    }
}
