// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.17.3
 * source: ethermint/feemarket/v1/genesis.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../gogoproto/gogo";
import * as dependency_2 from "./feemarket";
import * as pb_1 from "google-protobuf";
export namespace ethermint.feemarket.v1 {
    export class GenesisState extends pb_1.Message {
        constructor(data?: any[] | {
            params?: dependency_2.ethermint.feemarket.v1.Params;
            base_fee?: string;
            block_gas?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("params" in data && data.params != undefined) {
                    this.params = data.params;
                }
                if ("base_fee" in data && data.base_fee != undefined) {
                    this.base_fee = data.base_fee;
                }
                if ("block_gas" in data && data.block_gas != undefined) {
                    this.block_gas = data.block_gas;
                }
            }
        }
        get params() {
            return pb_1.Message.getWrapperField(this, dependency_2.ethermint.feemarket.v1.Params, 1) as dependency_2.ethermint.feemarket.v1.Params;
        }
        set params(value: dependency_2.ethermint.feemarket.v1.Params) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        get base_fee() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set base_fee(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get block_gas() {
            return pb_1.Message.getField(this, 3) as number;
        }
        set block_gas(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            params?: ReturnType<typeof dependency_2.ethermint.feemarket.v1.Params.prototype.toObject>;
            base_fee?: string;
            block_gas?: number;
        }) {
            const message = new GenesisState({});
            if (data.params != null) {
                message.params = dependency_2.ethermint.feemarket.v1.Params.fromObject(data.params);
            }
            if (data.base_fee != null) {
                message.base_fee = data.base_fee;
            }
            if (data.block_gas != null) {
                message.block_gas = data.block_gas;
            }
            return message;
        }
        toObject() {
            const data: {
                params?: ReturnType<typeof dependency_2.ethermint.feemarket.v1.Params.prototype.toObject>;
                base_fee?: string;
                block_gas?: number;
            } = {};
            if (this.params != null) {
                data.params = this.params.toObject();
            }
            if (this.base_fee != null) {
                data.base_fee = this.base_fee;
            }
            if (this.block_gas != null) {
                data.block_gas = this.block_gas;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.params !== undefined)
                writer.writeMessage(1, this.params, () => this.params.serialize(writer));
            if (typeof this.base_fee === "string" && this.base_fee.length)
                writer.writeString(2, this.base_fee);
            if (this.block_gas !== undefined)
                writer.writeUint64(3, this.block_gas);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GenesisState {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GenesisState();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.params, () => message.params = dependency_2.ethermint.feemarket.v1.Params.deserialize(reader));
                        break;
                    case 2:
                        message.base_fee = reader.readString();
                        break;
                    case 3:
                        message.block_gas = reader.readUint64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GenesisState {
            return GenesisState.deserialize(bytes);
        }
    }
}
