// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.8.0
 * source: cosmos/mint/v1beta1/mint.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../../gogoproto/gogo";
import * as dependency_2 from "./../../../cosmos_proto/cosmos";
import * as pb_1 from "google-protobuf";
export namespace cosmos.mint.v1beta1 {
    export class Minter extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            inflation?: string;
            annual_provisions?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("inflation" in data && data.inflation != undefined) {
                    this.inflation = data.inflation;
                }
                if ("annual_provisions" in data && data.annual_provisions != undefined) {
                    this.annual_provisions = data.annual_provisions;
                }
            }
        }
        get inflation() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set inflation(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get annual_provisions() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set annual_provisions(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            inflation?: string;
            annual_provisions?: string;
        }): Minter {
            const message = new Minter({});
            if (data.inflation != null) {
                message.inflation = data.inflation;
            }
            if (data.annual_provisions != null) {
                message.annual_provisions = data.annual_provisions;
            }
            return message;
        }
        toObject() {
            const data: {
                inflation?: string;
                annual_provisions?: string;
            } = {};
            if (this.inflation != null) {
                data.inflation = this.inflation;
            }
            if (this.annual_provisions != null) {
                data.annual_provisions = this.annual_provisions;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.inflation.length)
                writer.writeString(1, this.inflation);
            if (this.annual_provisions.length)
                writer.writeString(2, this.annual_provisions);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Minter {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Minter();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.inflation = reader.readString();
                        break;
                    case 2:
                        message.annual_provisions = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Minter {
            return Minter.deserialize(bytes);
        }
    }
    export class Params extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            mint_denom?: string;
            inflation_rate_change?: string;
            inflation_max?: string;
            inflation_min?: string;
            goal_bonded?: string;
            blocks_per_year?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("mint_denom" in data && data.mint_denom != undefined) {
                    this.mint_denom = data.mint_denom;
                }
                if ("inflation_rate_change" in data && data.inflation_rate_change != undefined) {
                    this.inflation_rate_change = data.inflation_rate_change;
                }
                if ("inflation_max" in data && data.inflation_max != undefined) {
                    this.inflation_max = data.inflation_max;
                }
                if ("inflation_min" in data && data.inflation_min != undefined) {
                    this.inflation_min = data.inflation_min;
                }
                if ("goal_bonded" in data && data.goal_bonded != undefined) {
                    this.goal_bonded = data.goal_bonded;
                }
                if ("blocks_per_year" in data && data.blocks_per_year != undefined) {
                    this.blocks_per_year = data.blocks_per_year;
                }
            }
        }
        get mint_denom() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set mint_denom(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get inflation_rate_change() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set inflation_rate_change(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get inflation_max() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set inflation_max(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get inflation_min() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set inflation_min(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get goal_bonded() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set goal_bonded(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get blocks_per_year() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set blocks_per_year(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        static fromObject(data: {
            mint_denom?: string;
            inflation_rate_change?: string;
            inflation_max?: string;
            inflation_min?: string;
            goal_bonded?: string;
            blocks_per_year?: number;
        }): Params {
            const message = new Params({});
            if (data.mint_denom != null) {
                message.mint_denom = data.mint_denom;
            }
            if (data.inflation_rate_change != null) {
                message.inflation_rate_change = data.inflation_rate_change;
            }
            if (data.inflation_max != null) {
                message.inflation_max = data.inflation_max;
            }
            if (data.inflation_min != null) {
                message.inflation_min = data.inflation_min;
            }
            if (data.goal_bonded != null) {
                message.goal_bonded = data.goal_bonded;
            }
            if (data.blocks_per_year != null) {
                message.blocks_per_year = data.blocks_per_year;
            }
            return message;
        }
        toObject() {
            const data: {
                mint_denom?: string;
                inflation_rate_change?: string;
                inflation_max?: string;
                inflation_min?: string;
                goal_bonded?: string;
                blocks_per_year?: number;
            } = {};
            if (this.mint_denom != null) {
                data.mint_denom = this.mint_denom;
            }
            if (this.inflation_rate_change != null) {
                data.inflation_rate_change = this.inflation_rate_change;
            }
            if (this.inflation_max != null) {
                data.inflation_max = this.inflation_max;
            }
            if (this.inflation_min != null) {
                data.inflation_min = this.inflation_min;
            }
            if (this.goal_bonded != null) {
                data.goal_bonded = this.goal_bonded;
            }
            if (this.blocks_per_year != null) {
                data.blocks_per_year = this.blocks_per_year;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.mint_denom.length)
                writer.writeString(1, this.mint_denom);
            if (this.inflation_rate_change.length)
                writer.writeString(2, this.inflation_rate_change);
            if (this.inflation_max.length)
                writer.writeString(3, this.inflation_max);
            if (this.inflation_min.length)
                writer.writeString(4, this.inflation_min);
            if (this.goal_bonded.length)
                writer.writeString(5, this.goal_bonded);
            if (this.blocks_per_year != 0)
                writer.writeUint64(6, this.blocks_per_year);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Params {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Params();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.mint_denom = reader.readString();
                        break;
                    case 2:
                        message.inflation_rate_change = reader.readString();
                        break;
                    case 3:
                        message.inflation_max = reader.readString();
                        break;
                    case 4:
                        message.inflation_min = reader.readString();
                        break;
                    case 5:
                        message.goal_bonded = reader.readString();
                        break;
                    case 6:
                        message.blocks_per_year = reader.readUint64();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Params {
            return Params.deserialize(bytes);
        }
    }
}
