// @ts-nocheck
/* eslint-disable */
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.4
 * source: cosmos/gov/v1beta1/gov.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./../../base/v1beta1/coin";
import * as dependency_4 from "./../../../google/protobuf/timestamp";
import * as dependency_5 from "./../../../google/protobuf/any";
import * as dependency_6 from "./../../../google/protobuf/duration";
import * as pb_1 from "google-protobuf";
export namespace cosmos.gov.v1beta1 {
    export enum VoteOption {
        VOTE_OPTION_UNSPECIFIED = 0,
        VOTE_OPTION_YES = 1,
        VOTE_OPTION_ABSTAIN = 2,
        VOTE_OPTION_NO = 3,
        VOTE_OPTION_NO_WITH_VETO = 4
    }
    export enum ProposalStatus {
        PROPOSAL_STATUS_UNSPECIFIED = 0,
        PROPOSAL_STATUS_DEPOSIT_PERIOD = 1,
        PROPOSAL_STATUS_VOTING_PERIOD = 2,
        PROPOSAL_STATUS_PASSED = 3,
        PROPOSAL_STATUS_REJECTED = 4,
        PROPOSAL_STATUS_FAILED = 5
    }
    export class WeightedVoteOption extends pb_1.Message {
        #one_of_decls = [];
        constructor(data?: any[] | {
            option?: VoteOption;
            weight?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("option" in data && data.option != undefined) {
                    this.option = data.option;
                }
                if ("weight" in data && data.weight != undefined) {
                    this.weight = data.weight;
                }
            }
        }
        get option() {
            return pb_1.Message.getField(this, 1) as VoteOption;
        }
        set option(value: VoteOption) {
            pb_1.Message.setField(this, 1, value);
        }
        get weight() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set weight(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            option?: VoteOption;
            weight?: string;
        }) {
            const message = new WeightedVoteOption({});
            if (data.option != null) {
                message.option = data.option;
            }
            if (data.weight != null) {
                message.weight = data.weight;
            }
            return message;
        }
        toObject() {
            const data: {
                option?: VoteOption;
                weight?: string;
            } = {};
            if (this.option != null) {
                data.option = this.option;
            }
            if (this.weight != null) {
                data.weight = this.weight;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.option !== undefined)
                writer.writeEnum(1, this.option);
            if (typeof this.weight === "string" && this.weight.length)
                writer.writeString(2, this.weight);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): WeightedVoteOption {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new WeightedVoteOption();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.option = reader.readEnum();
                        break;
                    case 2:
                        message.weight = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): WeightedVoteOption {
            return WeightedVoteOption.deserialize(bytes);
        }
    }
    export class TextProposal extends pb_1.Message {
        #one_of_decls = [];
        constructor(data?: any[] | {
            title?: string;
            description?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("title" in data && data.title != undefined) {
                    this.title = data.title;
                }
                if ("description" in data && data.description != undefined) {
                    this.description = data.description;
                }
            }
        }
        get title() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set title(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get description() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set description(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            title?: string;
            description?: string;
        }) {
            const message = new TextProposal({});
            if (data.title != null) {
                message.title = data.title;
            }
            if (data.description != null) {
                message.description = data.description;
            }
            return message;
        }
        toObject() {
            const data: {
                title?: string;
                description?: string;
            } = {};
            if (this.title != null) {
                data.title = this.title;
            }
            if (this.description != null) {
                data.description = this.description;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.title === "string" && this.title.length)
                writer.writeString(1, this.title);
            if (typeof this.description === "string" && this.description.length)
                writer.writeString(2, this.description);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TextProposal {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TextProposal();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.title = reader.readString();
                        break;
                    case 2:
                        message.description = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TextProposal {
            return TextProposal.deserialize(bytes);
        }
    }
    export class Deposit extends pb_1.Message {
        #one_of_decls = [];
        constructor(data?: any[] | {
            proposal_id?: number;
            depositor?: string;
            amount?: dependency_1.cosmos.base.v1beta1.Coin[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("proposal_id" in data && data.proposal_id != undefined) {
                    this.proposal_id = data.proposal_id;
                }
                if ("depositor" in data && data.depositor != undefined) {
                    this.depositor = data.depositor;
                }
                if ("amount" in data && data.amount != undefined) {
                    this.amount = data.amount;
                }
            }
        }
        get proposal_id() {
            return pb_1.Message.getField(this, 1) as number;
        }
        set proposal_id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get depositor() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set depositor(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get amount() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_1.cosmos.base.v1beta1.Coin, 3) as dependency_1.cosmos.base.v1beta1.Coin[];
        }
        set amount(value: dependency_1.cosmos.base.v1beta1.Coin[]) {
            pb_1.Message.setRepeatedWrapperField(this, 3, value);
        }
        static fromObject(data: {
            proposal_id?: number;
            depositor?: string;
            amount?: ReturnType<typeof dependency_1.cosmos.base.v1beta1.Coin.prototype.toObject>[];
        }) {
            const message = new Deposit({});
            if (data.proposal_id != null) {
                message.proposal_id = data.proposal_id;
            }
            if (data.depositor != null) {
                message.depositor = data.depositor;
            }
            if (data.amount != null) {
                message.amount = data.amount.map(item => dependency_1.cosmos.base.v1beta1.Coin.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                proposal_id?: number;
                depositor?: string;
                amount?: ReturnType<typeof dependency_1.cosmos.base.v1beta1.Coin.prototype.toObject>[];
            } = {};
            if (this.proposal_id != null) {
                data.proposal_id = this.proposal_id;
            }
            if (this.depositor != null) {
                data.depositor = this.depositor;
            }
            if (this.amount != null) {
                data.amount = this.amount.map((item: dependency_1.cosmos.base.v1beta1.Coin) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.proposal_id !== undefined)
                writer.writeUint64(1, this.proposal_id);
            if (typeof this.depositor === "string" && this.depositor.length)
                writer.writeString(2, this.depositor);
            if (this.amount !== undefined)
                writer.writeRepeatedMessage(3, this.amount, (item: dependency_1.cosmos.base.v1beta1.Coin) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Deposit {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Deposit();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.proposal_id = reader.readUint64();
                        break;
                    case 2:
                        message.depositor = reader.readString();
                        break;
                    case 3:
                        reader.readMessage(message.amount, () => pb_1.Message.addToRepeatedWrapperField(message, 3, dependency_1.cosmos.base.v1beta1.Coin.deserialize(reader), dependency_1.cosmos.base.v1beta1.Coin));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Deposit {
            return Deposit.deserialize(bytes);
        }
    }
    export class Proposal extends pb_1.Message {
        #one_of_decls = [];
        constructor(data?: any[] | {
            proposal_id?: number;
            content?: dependency_5.google.protobuf.Any;
            status?: ProposalStatus;
            final_tally_result?: TallyResult;
            submit_time?: dependency_4.google.protobuf.Timestamp;
            deposit_end_time?: dependency_4.google.protobuf.Timestamp;
            total_deposit?: dependency_1.cosmos.base.v1beta1.Coin[];
            voting_start_time?: dependency_4.google.protobuf.Timestamp;
            voting_end_time?: dependency_4.google.protobuf.Timestamp;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [7], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("proposal_id" in data && data.proposal_id != undefined) {
                    this.proposal_id = data.proposal_id;
                }
                if ("content" in data && data.content != undefined) {
                    this.content = data.content;
                }
                if ("status" in data && data.status != undefined) {
                    this.status = data.status;
                }
                if ("final_tally_result" in data && data.final_tally_result != undefined) {
                    this.final_tally_result = data.final_tally_result;
                }
                if ("submit_time" in data && data.submit_time != undefined) {
                    this.submit_time = data.submit_time;
                }
                if ("deposit_end_time" in data && data.deposit_end_time != undefined) {
                    this.deposit_end_time = data.deposit_end_time;
                }
                if ("total_deposit" in data && data.total_deposit != undefined) {
                    this.total_deposit = data.total_deposit;
                }
                if ("voting_start_time" in data && data.voting_start_time != undefined) {
                    this.voting_start_time = data.voting_start_time;
                }
                if ("voting_end_time" in data && data.voting_end_time != undefined) {
                    this.voting_end_time = data.voting_end_time;
                }
            }
        }
        get proposal_id() {
            return pb_1.Message.getField(this, 1) as number;
        }
        set proposal_id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get content() {
            return pb_1.Message.getWrapperField(this, dependency_5.google.protobuf.Any, 2) as dependency_5.google.protobuf.Any;
        }
        set content(value: dependency_5.google.protobuf.Any) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        get status() {
            return pb_1.Message.getField(this, 3) as ProposalStatus;
        }
        set status(value: ProposalStatus) {
            pb_1.Message.setField(this, 3, value);
        }
        get final_tally_result() {
            return pb_1.Message.getWrapperField(this, TallyResult, 4) as TallyResult;
        }
        set final_tally_result(value: TallyResult) {
            pb_1.Message.setWrapperField(this, 4, value);
        }
        get submit_time() {
            return pb_1.Message.getWrapperField(this, dependency_4.google.protobuf.Timestamp, 5) as dependency_4.google.protobuf.Timestamp;
        }
        set submit_time(value: dependency_4.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 5, value);
        }
        get deposit_end_time() {
            return pb_1.Message.getWrapperField(this, dependency_4.google.protobuf.Timestamp, 6) as dependency_4.google.protobuf.Timestamp;
        }
        set deposit_end_time(value: dependency_4.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 6, value);
        }
        get total_deposit() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_1.cosmos.base.v1beta1.Coin, 7) as dependency_1.cosmos.base.v1beta1.Coin[];
        }
        set total_deposit(value: dependency_1.cosmos.base.v1beta1.Coin[]) {
            pb_1.Message.setRepeatedWrapperField(this, 7, value);
        }
        get voting_start_time() {
            return pb_1.Message.getWrapperField(this, dependency_4.google.protobuf.Timestamp, 8) as dependency_4.google.protobuf.Timestamp;
        }
        set voting_start_time(value: dependency_4.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 8, value);
        }
        get voting_end_time() {
            return pb_1.Message.getWrapperField(this, dependency_4.google.protobuf.Timestamp, 9) as dependency_4.google.protobuf.Timestamp;
        }
        set voting_end_time(value: dependency_4.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 9, value);
        }
        static fromObject(data: {
            proposal_id?: number;
            content?: ReturnType<typeof dependency_5.google.protobuf.Any.prototype.toObject>;
            status?: ProposalStatus;
            final_tally_result?: ReturnType<typeof TallyResult.prototype.toObject>;
            submit_time?: ReturnType<typeof dependency_4.google.protobuf.Timestamp.prototype.toObject>;
            deposit_end_time?: ReturnType<typeof dependency_4.google.protobuf.Timestamp.prototype.toObject>;
            total_deposit?: ReturnType<typeof dependency_1.cosmos.base.v1beta1.Coin.prototype.toObject>[];
            voting_start_time?: ReturnType<typeof dependency_4.google.protobuf.Timestamp.prototype.toObject>;
            voting_end_time?: ReturnType<typeof dependency_4.google.protobuf.Timestamp.prototype.toObject>;
        }) {
            const message = new Proposal({});
            if (data.proposal_id != null) {
                message.proposal_id = data.proposal_id;
            }
            if (data.content != null) {
                message.content = dependency_5.google.protobuf.Any.fromObject(data.content);
            }
            if (data.status != null) {
                message.status = data.status;
            }
            if (data.final_tally_result != null) {
                message.final_tally_result = TallyResult.fromObject(data.final_tally_result);
            }
            if (data.submit_time != null) {
                message.submit_time = dependency_4.google.protobuf.Timestamp.fromObject(data.submit_time);
            }
            if (data.deposit_end_time != null) {
                message.deposit_end_time = dependency_4.google.protobuf.Timestamp.fromObject(data.deposit_end_time);
            }
            if (data.total_deposit != null) {
                message.total_deposit = data.total_deposit.map(item => dependency_1.cosmos.base.v1beta1.Coin.fromObject(item));
            }
            if (data.voting_start_time != null) {
                message.voting_start_time = dependency_4.google.protobuf.Timestamp.fromObject(data.voting_start_time);
            }
            if (data.voting_end_time != null) {
                message.voting_end_time = dependency_4.google.protobuf.Timestamp.fromObject(data.voting_end_time);
            }
            return message;
        }
        toObject() {
            const data: {
                proposal_id?: number;
                content?: ReturnType<typeof dependency_5.google.protobuf.Any.prototype.toObject>;
                status?: ProposalStatus;
                final_tally_result?: ReturnType<typeof TallyResult.prototype.toObject>;
                submit_time?: ReturnType<typeof dependency_4.google.protobuf.Timestamp.prototype.toObject>;
                deposit_end_time?: ReturnType<typeof dependency_4.google.protobuf.Timestamp.prototype.toObject>;
                total_deposit?: ReturnType<typeof dependency_1.cosmos.base.v1beta1.Coin.prototype.toObject>[];
                voting_start_time?: ReturnType<typeof dependency_4.google.protobuf.Timestamp.prototype.toObject>;
                voting_end_time?: ReturnType<typeof dependency_4.google.protobuf.Timestamp.prototype.toObject>;
            } = {};
            if (this.proposal_id != null) {
                data.proposal_id = this.proposal_id;
            }
            if (this.content != null) {
                data.content = this.content.toObject();
            }
            if (this.status != null) {
                data.status = this.status;
            }
            if (this.final_tally_result != null) {
                data.final_tally_result = this.final_tally_result.toObject();
            }
            if (this.submit_time != null) {
                data.submit_time = this.submit_time.toObject();
            }
            if (this.deposit_end_time != null) {
                data.deposit_end_time = this.deposit_end_time.toObject();
            }
            if (this.total_deposit != null) {
                data.total_deposit = this.total_deposit.map((item: dependency_1.cosmos.base.v1beta1.Coin) => item.toObject());
            }
            if (this.voting_start_time != null) {
                data.voting_start_time = this.voting_start_time.toObject();
            }
            if (this.voting_end_time != null) {
                data.voting_end_time = this.voting_end_time.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.proposal_id !== undefined)
                writer.writeUint64(1, this.proposal_id);
            if (this.content !== undefined)
                writer.writeMessage(2, this.content, () => this.content.serialize(writer));
            if (this.status !== undefined)
                writer.writeEnum(3, this.status);
            if (this.final_tally_result !== undefined)
                writer.writeMessage(4, this.final_tally_result, () => this.final_tally_result.serialize(writer));
            if (this.submit_time !== undefined)
                writer.writeMessage(5, this.submit_time, () => this.submit_time.serialize(writer));
            if (this.deposit_end_time !== undefined)
                writer.writeMessage(6, this.deposit_end_time, () => this.deposit_end_time.serialize(writer));
            if (this.total_deposit !== undefined)
                writer.writeRepeatedMessage(7, this.total_deposit, (item: dependency_1.cosmos.base.v1beta1.Coin) => item.serialize(writer));
            if (this.voting_start_time !== undefined)
                writer.writeMessage(8, this.voting_start_time, () => this.voting_start_time.serialize(writer));
            if (this.voting_end_time !== undefined)
                writer.writeMessage(9, this.voting_end_time, () => this.voting_end_time.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Proposal {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Proposal();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.proposal_id = reader.readUint64();
                        break;
                    case 2:
                        reader.readMessage(message.content, () => message.content = dependency_5.google.protobuf.Any.deserialize(reader));
                        break;
                    case 3:
                        message.status = reader.readEnum();
                        break;
                    case 4:
                        reader.readMessage(message.final_tally_result, () => message.final_tally_result = TallyResult.deserialize(reader));
                        break;
                    case 5:
                        reader.readMessage(message.submit_time, () => message.submit_time = dependency_4.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 6:
                        reader.readMessage(message.deposit_end_time, () => message.deposit_end_time = dependency_4.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 7:
                        reader.readMessage(message.total_deposit, () => pb_1.Message.addToRepeatedWrapperField(message, 7, dependency_1.cosmos.base.v1beta1.Coin.deserialize(reader), dependency_1.cosmos.base.v1beta1.Coin));
                        break;
                    case 8:
                        reader.readMessage(message.voting_start_time, () => message.voting_start_time = dependency_4.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 9:
                        reader.readMessage(message.voting_end_time, () => message.voting_end_time = dependency_4.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Proposal {
            return Proposal.deserialize(bytes);
        }
    }
    export class TallyResult extends pb_1.Message {
        #one_of_decls = [];
        constructor(data?: any[] | {
            yes?: string;
            abstain?: string;
            no?: string;
            no_with_veto?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("yes" in data && data.yes != undefined) {
                    this.yes = data.yes;
                }
                if ("abstain" in data && data.abstain != undefined) {
                    this.abstain = data.abstain;
                }
                if ("no" in data && data.no != undefined) {
                    this.no = data.no;
                }
                if ("no_with_veto" in data && data.no_with_veto != undefined) {
                    this.no_with_veto = data.no_with_veto;
                }
            }
        }
        get yes() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set yes(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get abstain() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set abstain(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get no() {
            return pb_1.Message.getField(this, 3) as string;
        }
        set no(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get no_with_veto() {
            return pb_1.Message.getField(this, 4) as string;
        }
        set no_with_veto(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        static fromObject(data: {
            yes?: string;
            abstain?: string;
            no?: string;
            no_with_veto?: string;
        }) {
            const message = new TallyResult({});
            if (data.yes != null) {
                message.yes = data.yes;
            }
            if (data.abstain != null) {
                message.abstain = data.abstain;
            }
            if (data.no != null) {
                message.no = data.no;
            }
            if (data.no_with_veto != null) {
                message.no_with_veto = data.no_with_veto;
            }
            return message;
        }
        toObject() {
            const data: {
                yes?: string;
                abstain?: string;
                no?: string;
                no_with_veto?: string;
            } = {};
            if (this.yes != null) {
                data.yes = this.yes;
            }
            if (this.abstain != null) {
                data.abstain = this.abstain;
            }
            if (this.no != null) {
                data.no = this.no;
            }
            if (this.no_with_veto != null) {
                data.no_with_veto = this.no_with_veto;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.yes === "string" && this.yes.length)
                writer.writeString(1, this.yes);
            if (typeof this.abstain === "string" && this.abstain.length)
                writer.writeString(2, this.abstain);
            if (typeof this.no === "string" && this.no.length)
                writer.writeString(3, this.no);
            if (typeof this.no_with_veto === "string" && this.no_with_veto.length)
                writer.writeString(4, this.no_with_veto);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TallyResult {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TallyResult();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.yes = reader.readString();
                        break;
                    case 2:
                        message.abstain = reader.readString();
                        break;
                    case 3:
                        message.no = reader.readString();
                        break;
                    case 4:
                        message.no_with_veto = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TallyResult {
            return TallyResult.deserialize(bytes);
        }
    }
    export class Vote extends pb_1.Message {
        #one_of_decls = [];
        constructor(data?: any[] | {
            proposal_id?: number;
            voter?: string;
            /** @deprecated*/
            option?: VoteOption;
            options?: WeightedVoteOption[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [4], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("proposal_id" in data && data.proposal_id != undefined) {
                    this.proposal_id = data.proposal_id;
                }
                if ("voter" in data && data.voter != undefined) {
                    this.voter = data.voter;
                }
                if ("option" in data && data.option != undefined) {
                    this.option = data.option;
                }
                if ("options" in data && data.options != undefined) {
                    this.options = data.options;
                }
            }
        }
        get proposal_id() {
            return pb_1.Message.getField(this, 1) as number;
        }
        set proposal_id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get voter() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set voter(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        /** @deprecated*/
        get option() {
            return pb_1.Message.getField(this, 3) as VoteOption;
        }
        /** @deprecated*/
        set option(value: VoteOption) {
            pb_1.Message.setField(this, 3, value);
        }
        get options() {
            return pb_1.Message.getRepeatedWrapperField(this, WeightedVoteOption, 4) as WeightedVoteOption[];
        }
        set options(value: WeightedVoteOption[]) {
            pb_1.Message.setRepeatedWrapperField(this, 4, value);
        }
        static fromObject(data: {
            proposal_id?: number;
            voter?: string;
            option?: VoteOption;
            options?: ReturnType<typeof WeightedVoteOption.prototype.toObject>[];
        }) {
            const message = new Vote({});
            if (data.proposal_id != null) {
                message.proposal_id = data.proposal_id;
            }
            if (data.voter != null) {
                message.voter = data.voter;
            }
            if (data.option != null) {
                message.option = data.option;
            }
            if (data.options != null) {
                message.options = data.options.map(item => WeightedVoteOption.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                proposal_id?: number;
                voter?: string;
                option?: VoteOption;
                options?: ReturnType<typeof WeightedVoteOption.prototype.toObject>[];
            } = {};
            if (this.proposal_id != null) {
                data.proposal_id = this.proposal_id;
            }
            if (this.voter != null) {
                data.voter = this.voter;
            }
            if (this.option != null) {
                data.option = this.option;
            }
            if (this.options != null) {
                data.options = this.options.map((item: WeightedVoteOption) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.proposal_id !== undefined)
                writer.writeUint64(1, this.proposal_id);
            if (typeof this.voter === "string" && this.voter.length)
                writer.writeString(2, this.voter);
            if (this.option !== undefined)
                writer.writeEnum(3, this.option);
            if (this.options !== undefined)
                writer.writeRepeatedMessage(4, this.options, (item: WeightedVoteOption) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Vote {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Vote();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.proposal_id = reader.readUint64();
                        break;
                    case 2:
                        message.voter = reader.readString();
                        break;
                    case 3:
                        message.option = reader.readEnum();
                        break;
                    case 4:
                        reader.readMessage(message.options, () => pb_1.Message.addToRepeatedWrapperField(message, 4, WeightedVoteOption.deserialize(reader), WeightedVoteOption));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Vote {
            return Vote.deserialize(bytes);
        }
    }
    export class DepositParams extends pb_1.Message {
        #one_of_decls = [];
        constructor(data?: any[] | {
            min_deposit?: dependency_1.cosmos.base.v1beta1.Coin[];
            max_deposit_period?: dependency_6.google.protobuf.Duration;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("min_deposit" in data && data.min_deposit != undefined) {
                    this.min_deposit = data.min_deposit;
                }
                if ("max_deposit_period" in data && data.max_deposit_period != undefined) {
                    this.max_deposit_period = data.max_deposit_period;
                }
            }
        }
        get min_deposit() {
            return pb_1.Message.getRepeatedWrapperField(this, dependency_1.cosmos.base.v1beta1.Coin, 1) as dependency_1.cosmos.base.v1beta1.Coin[];
        }
        set min_deposit(value: dependency_1.cosmos.base.v1beta1.Coin[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        get max_deposit_period() {
            return pb_1.Message.getWrapperField(this, dependency_6.google.protobuf.Duration, 2) as dependency_6.google.protobuf.Duration;
        }
        set max_deposit_period(value: dependency_6.google.protobuf.Duration) {
            pb_1.Message.setWrapperField(this, 2, value);
        }
        static fromObject(data: {
            min_deposit?: ReturnType<typeof dependency_1.cosmos.base.v1beta1.Coin.prototype.toObject>[];
            max_deposit_period?: ReturnType<typeof dependency_6.google.protobuf.Duration.prototype.toObject>;
        }) {
            const message = new DepositParams({});
            if (data.min_deposit != null) {
                message.min_deposit = data.min_deposit.map(item => dependency_1.cosmos.base.v1beta1.Coin.fromObject(item));
            }
            if (data.max_deposit_period != null) {
                message.max_deposit_period = dependency_6.google.protobuf.Duration.fromObject(data.max_deposit_period);
            }
            return message;
        }
        toObject() {
            const data: {
                min_deposit?: ReturnType<typeof dependency_1.cosmos.base.v1beta1.Coin.prototype.toObject>[];
                max_deposit_period?: ReturnType<typeof dependency_6.google.protobuf.Duration.prototype.toObject>;
            } = {};
            if (this.min_deposit != null) {
                data.min_deposit = this.min_deposit.map((item: dependency_1.cosmos.base.v1beta1.Coin) => item.toObject());
            }
            if (this.max_deposit_period != null) {
                data.max_deposit_period = this.max_deposit_period.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.min_deposit !== undefined)
                writer.writeRepeatedMessage(1, this.min_deposit, (item: dependency_1.cosmos.base.v1beta1.Coin) => item.serialize(writer));
            if (this.max_deposit_period !== undefined)
                writer.writeMessage(2, this.max_deposit_period, () => this.max_deposit_period.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DepositParams {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DepositParams();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.min_deposit, () => pb_1.Message.addToRepeatedWrapperField(message, 1, dependency_1.cosmos.base.v1beta1.Coin.deserialize(reader), dependency_1.cosmos.base.v1beta1.Coin));
                        break;
                    case 2:
                        reader.readMessage(message.max_deposit_period, () => message.max_deposit_period = dependency_6.google.protobuf.Duration.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DepositParams {
            return DepositParams.deserialize(bytes);
        }
    }
    export class VotingParams extends pb_1.Message {
        #one_of_decls = [];
        constructor(data?: any[] | {
            voting_period?: dependency_6.google.protobuf.Duration;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("voting_period" in data && data.voting_period != undefined) {
                    this.voting_period = data.voting_period;
                }
            }
        }
        get voting_period() {
            return pb_1.Message.getWrapperField(this, dependency_6.google.protobuf.Duration, 1) as dependency_6.google.protobuf.Duration;
        }
        set voting_period(value: dependency_6.google.protobuf.Duration) {
            pb_1.Message.setWrapperField(this, 1, value);
        }
        static fromObject(data: {
            voting_period?: ReturnType<typeof dependency_6.google.protobuf.Duration.prototype.toObject>;
        }) {
            const message = new VotingParams({});
            if (data.voting_period != null) {
                message.voting_period = dependency_6.google.protobuf.Duration.fromObject(data.voting_period);
            }
            return message;
        }
        toObject() {
            const data: {
                voting_period?: ReturnType<typeof dependency_6.google.protobuf.Duration.prototype.toObject>;
            } = {};
            if (this.voting_period != null) {
                data.voting_period = this.voting_period.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.voting_period !== undefined)
                writer.writeMessage(1, this.voting_period, () => this.voting_period.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): VotingParams {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new VotingParams();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.voting_period, () => message.voting_period = dependency_6.google.protobuf.Duration.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): VotingParams {
            return VotingParams.deserialize(bytes);
        }
    }
    export class TallyParams extends pb_1.Message {
        #one_of_decls = [];
        constructor(data?: any[] | {
            quorum?: Uint8Array;
            threshold?: Uint8Array;
            veto_threshold?: Uint8Array;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("quorum" in data && data.quorum != undefined) {
                    this.quorum = data.quorum;
                }
                if ("threshold" in data && data.threshold != undefined) {
                    this.threshold = data.threshold;
                }
                if ("veto_threshold" in data && data.veto_threshold != undefined) {
                    this.veto_threshold = data.veto_threshold;
                }
            }
        }
        get quorum() {
            return pb_1.Message.getField(this, 1) as Uint8Array;
        }
        set quorum(value: Uint8Array) {
            pb_1.Message.setField(this, 1, value);
        }
        get threshold() {
            return pb_1.Message.getField(this, 2) as Uint8Array;
        }
        set threshold(value: Uint8Array) {
            pb_1.Message.setField(this, 2, value);
        }
        get veto_threshold() {
            return pb_1.Message.getField(this, 3) as Uint8Array;
        }
        set veto_threshold(value: Uint8Array) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            quorum?: Uint8Array;
            threshold?: Uint8Array;
            veto_threshold?: Uint8Array;
        }) {
            const message = new TallyParams({});
            if (data.quorum != null) {
                message.quorum = data.quorum;
            }
            if (data.threshold != null) {
                message.threshold = data.threshold;
            }
            if (data.veto_threshold != null) {
                message.veto_threshold = data.veto_threshold;
            }
            return message;
        }
        toObject() {
            const data: {
                quorum?: Uint8Array;
                threshold?: Uint8Array;
                veto_threshold?: Uint8Array;
            } = {};
            if (this.quorum != null) {
                data.quorum = this.quorum;
            }
            if (this.threshold != null) {
                data.threshold = this.threshold;
            }
            if (this.veto_threshold != null) {
                data.veto_threshold = this.veto_threshold;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.quorum !== undefined)
                writer.writeBytes(1, this.quorum);
            if (this.threshold !== undefined)
                writer.writeBytes(2, this.threshold);
            if (this.veto_threshold !== undefined)
                writer.writeBytes(3, this.veto_threshold);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TallyParams {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TallyParams();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.quorum = reader.readBytes();
                        break;
                    case 2:
                        message.threshold = reader.readBytes();
                        break;
                    case 3:
                        message.veto_threshold = reader.readBytes();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TallyParams {
            return TallyParams.deserialize(bytes);
        }
    }
}
