name: ESLint
on:
  pull_request:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install -g
      - name: Run ESLint
        run: eslint ./packages/**/*.{ts,js}
