name: Test
on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: technote-space/get-diff-action@v6.0.1
        id: git_diff
        with:
          PATTERNS: |
            packages/**/**.js
            packages/**/**.ts
            packages/**/package.json
            packages/**/yarn.lock
            package.json
            yarn.lock

      - name: Install modules
        run: npm install
        if: env.GIT_DIFF

      - name: NPM build is needed because the packages inter-dependencies
        run: npm run build
        if: env.GIT_DIFF

      - name: Start Docker network tests
        run: >-
          cd packages/evmosjs/src/tests &&
          docker build -t evmosjs-test . &&
          docker create -p 1317:1317 -p 8545:8545 --name evmos -t evmosjs-test &&
          docker start evmos &&
          cd ../../../..
        if: env.GIT_DIFF

      - name: Wait for Docker to spin up
        run: sleep 30s
        if: env.GIT_DIFF

      - name: Run tests
        run: npm run test
        if: env.GIT_DIFF
